theme: jekyll-theme-hacker
title: pseudo geek
description: random hacks and tech stuff

permalink: pretty

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

url: https://samirkut.github.io

excerpt_separator: "<!--more-->"

#author details
Samir:
  name: Samir Kuthiala
  email: samir.kuthiala@gmail.com
  web: http://twitter.com/samirkut
